-- 旧 DbInitListener の Java 埋め込み DDL / シードデータを Flyway 管理に移行。
-- H2 (demo) / PostgreSQL (postgres) 双方で動作する SQL のみを使用する。

CREATE TABLE product (
    id             INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku            VARCHAR(50)  NOT NULL,
    name           VARCHAR(200) NOT NULL,
    price          NUMERIC(15, 2) NOT NULL,
    stock_quantity INTEGER      NOT NULL
);

CREATE TABLE customer (
    id    INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(200) NOT NULL,
    email VARCHAR(200)
);

CREATE TABLE orders (
    id            INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR(200) NOT NULL,
    order_date    DATE         NOT NULL,
    status        VARCHAR(20)  NOT NULL
);

CREATE TABLE order_item (
    id           INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     INTEGER      NOT NULL REFERENCES orders (id),
    product_id   INTEGER      NOT NULL,
    product_name VARCHAR(200) NOT NULL,
    unit_price   NUMERIC(15, 2) NOT NULL,
    quantity     INTEGER      NOT NULL
);

CREATE INDEX idx_order_item_order_id ON order_item (order_id);

INSERT INTO product (sku, name, price, stock_quantity) VALUES
    ('SKU-1001', 'ノートPC 14インチ', 128000, 24),
    ('SKU-1002', 'ワイヤレスマウス', 2800, 6),
    ('SKU-1003', 'USB-Cハブ (7in1)', 4500, 3),
    ('SKU-1004', '外付けSSD 1TB', 15800, 40),
    ('SKU-1005', 'モニター 27インチ 4K', 46000, 8),
    ('SKU-1006', 'メカニカルキーボード', 9800, 15);

INSERT INTO customer (name, email) VALUES
    ('株式会社サンプル商事', 'order@sample-shoji.example.co.jp'),
    ('合同会社デモロジスティクス', 'contact@demo-logistics.example.co.jp');

INSERT INTO orders (customer_name, order_date, status) VALUES
    ('株式会社サンプル商事', DATE '2026-07-20', 'SHIPPED');

INSERT INTO order_item (order_id, product_id, product_name, unit_price, quantity)
SELECT o.id, p.id, p.name, p.price, 2
FROM orders o, product p
WHERE o.customer_name = '株式会社サンプル商事' AND p.sku = 'SKU-1001';

INSERT INTO order_item (order_id, product_id, product_name, unit_price, quantity)
SELECT o.id, p.id, p.name, p.price, 2
FROM orders o, product p
WHERE o.customer_name = '株式会社サンプル商事' AND p.sku = 'SKU-1002';
